# .github/workflows/ci.yml

name: CI/CD Pipeline for Data cleaning

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Instalacja Python i zależności
      - name: Python config
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      # Krok 3: Uruchomienie skryptu
      - name: Run data cleaning
        env:
          API_KEY: ${{ secrets.LAB2_API_KEY }}
        run: python s24365.py

      # Krok 4: Wyświetlenie raportu z czyszczenia danych
      - name: Display report
        run: cat report.txt