# .github/workflows/ci.yml

name: CI/CD Pipeline for Data prediction

# Wykonuj akcje on demand
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  data-prediction:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Instalacja Python i zależności
      - name: Python config
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      # Krok 3: Generowanie wykresów
      - name: Run prediction
        run: python generate_plots.py
        
      # Krok 4: Uruchomienie predykcji
      - name: Run prediction
        run: python train_model.py

      # Krok 5: Wyświetlenie wyników modelu
      - name: Display report
        run: cat results.txt
